### PR TITLE
fix <language> tags in component level

### PR DESCRIPTION
**Pull request by andyzyl321**
Fixes #issuenumber ; refs #issuenumber

# Summary 
A short description of the feature

# Related Issue
Use # to add a quick link to the parent issue(s), or ! for parent merge requests. Also, go to that issue and edit the description to mention this MR.

# Expected Behavior

Demo how this merge request is working in the app. Consult the acceptance criteria in the issue. 

# Screenshots / Video
Include screenshots or video demonstrating how this feature works

# Dependencies

Are there any other outstanding issues which need to be resolved before this can be merged?

# Side Effects

Will the changes in this merge request potentially impact any thing else that isn't explicitly part of this feature? 

# Testing / Reproduction instructions

Step by step instructions on how to test this feature. Include links and username/passswords if necessary. Videos are especially helpful. Also, name any spec files that should be run for this feature, or to test any side effects from this feature.

1. Go here
2. Do this
3. Observe this behavior

# Deployment

Where is this deployed? Are there any additional steps to get this working on staging/production? (e.g. setting up enviromental variables)

# Other Information

Any other logs, related issues, merge requests, wireframes, documentation, slack conversations or anything else that would help the developer try to find and fix this issue, or provide context.

### CODE REVIEW

**Comment by jlhardes** [comment]
These changes are on ArcLight dev and you can see language showing at the component level in University Archives > Hubert C. Heffner Papers > Correspondence, 1920-1978 > General (chronological) > 1920-1922. That Language information is not currently showing on Arclight prod.

**Comment by andyzyl321** [comment]
> These changes are on ArcLight dev and you can see language showing at the component level in University Archives > Hubert C. Heffner Papers > Correspondence, 1920-1978 > General (chronological) > 1920-1922. That Language information is not currently showing on Arclight prod. This connects to https://bugs.dlib.indiana.edu/browse/AR-68

Hi Julie,

 I have no access to [Jira](https://bugs.dlib.indiana.edu/browse/AR-68). What's the relationship between Arclight dev and Arclight prod?

Best,

**Comment by jlhardes** [comment]
Hi Zhengyi - These are notes for merging. The Jira issue is connecting your work to the list of things we're working on overall for ArcLight at IU, which we're tracking in Jira. I don't think you need access to that but I will talk to the team today about that. ArcLight dev is the instance where you are working and trying out code changes. ArcLight prod is a different instance we have set up. So this is noting that these code changes are in one place already but not the other. Does that help?

**Comment by andyzyl321** [comment]
> Hi Zhengyi - These are notes for merging. The Jira issue is connecting your work to the list of things we're working on overall for ArcLight at IU, which we're tracking in Jira. I don't think you need access to that but I will talk to the team today about that. ArcLight dev is the instance where you are working and trying out code changes. ArcLight prod is a different instance we have set up. So this is noting that these code changes are in one place already but not the other. Does that help?

Hi Julie,

Thanks for explanation! I thought it was something about <language> could be shown up at one Arclight platform while can't on the other, which has a different structure so the solution to <language> problem doesn't work on ArcLight prod. Feel free to let me know if you have any question.

Best,

**Pull request merged**
